### Read all pizzas with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/mymovies

### Filter movies by minimum duration
GET {{baseUrl}}/mymovies?minimum-duration=110

### GET one specific movie by id
GET {{baseUrl}}/mymovies/2

### Create and add a new movie
POST {{baseUrl}}/mymovies/
Content-Type: application/json

{
    "title":"DeadPool",
    "duration":148,
    "budget":58,
    "link":"https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi-pNj9geaBAxXK1gIHHQzMAnAQFnoECCcQAQ&url=https%3A%2F%2Fwww.allocine.fr%2Farticle%2Ffichearticle_gen_carticle%3D18695740.html&usg=AOvVaw2uoJ7oZKJTnBzcH98DNTRR&opi=89978449"
}

### Create a film
POST {{baseUrl}}/mymovies/
Content-Type: application/json

{
    "title":"Star Wars: The Phantom Menace (Episode I)",
    "duration": 136,
    "budget": 115,
    "link":"https://en.wikipedia.org/wiki/Star_Wars:_Episode_I_%E2%80%93_The_Phantom_Menace"
}


### Create a movie
POST {{baseUrl}}/mymovies/
Content-Type:  application/json

{
    "title":"Gran Turismo",
    "duration": 135,
    "budget": 60,
    "link":"blablabla"
}